[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bb_hpc"
version = "0.0.1"
description = "Beesbook HPC orchestration (slurm + kubernetes)"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]   